// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sigil Contributors

package types

// Origin indicates the source of content being scanned or the source of a
// conversation message. Used for context-aware logging and rule selection.
//
// Empty string represents unknown/legacy origin for messages created before
// origin tracking was introduced. Callers should explicitly set Origin rather
// than relying on the fallback via originFromRole().
type Origin string

const (
	// OriginUserInput indicates content originating from a human user.
	OriginUserInput Origin = "user_input"
	// OriginSystem indicates content generated by the system or assistant (e.g., LLM responses persisted to session history).
	OriginSystem Origin = "system"
	// OriginToolOutput indicates content originating from a tool call result.
	OriginToolOutput Origin = "tool_output"
)

// Valid reports whether the origin is a known content origin.
func (o Origin) Valid() bool {
	switch o {
	case OriginUserInput, OriginSystem, OriginToolOutput:
		return true
	default:
		return false
	}
}
