// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sigil Contributors

package types

import (
	"strings"

	sigilerr "github.com/sigil-dev/sigil/pkg/errors"
)

// ScannerMode defines how the security scanner handles detected threats.
type ScannerMode string

const (
	ScannerModeBlock  ScannerMode = "block"
	ScannerModeFlag   ScannerMode = "flag"
	ScannerModeRedact ScannerMode = "redact"
)

// Valid reports whether m is a recognized scanner mode.
func (m ScannerMode) Valid() bool {
	switch m {
	case ScannerModeBlock, ScannerModeFlag, ScannerModeRedact:
		return true
	default:
		return false
	}
}

// ParseScannerMode parses a case-insensitive string into a ScannerMode.
func ParseScannerMode(s string) (ScannerMode, error) {
	m := ScannerMode(strings.ToLower(s))
	if !m.Valid() {
		return "", sigilerr.Errorf(sigilerr.CodeConfigValidateInvalidValue,
			"invalid scanner mode: %q", s)
	}
	return m, nil
}

// Origin indicates the source of content being scanned or the source of a
// conversation message. Used for context-aware logging and rule selection.
//
// Empty string represents unknown/legacy origin for messages created before
// origin tracking was introduced. Callers should explicitly set Origin rather
// than relying on the fallback via originFromRole().
type Origin string

const (
	// OriginUserInput indicates content originating from a human user.
	OriginUserInput Origin = "user_input"
	// OriginSystem indicates content generated by the system or assistant (e.g., LLM responses persisted to session history).
	OriginSystem Origin = "system"
	// OriginToolOutput indicates content originating from a tool call result.
	OriginToolOutput Origin = "tool_output"
)

// Valid reports whether the origin is a known content origin.
func (o Origin) Valid() bool {
	switch o {
	case OriginUserInput, OriginSystem, OriginToolOutput:
		return true
	default:
		return false
	}
}
